logging:
  enabled: true
  level: log

server:
  externalDomain: https://immich.lab.omglolwtfbbq.com

backup:
  database:
    enabled: false # managed externally

storageTemplate:
  enabled: true
  hashVerificationEnabled: true
  template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"

trash:
  enabled: true
  days: 30

oauth:
  enabled: true
  buttonText: Login with Authentik
  issuerUrl: https://auth.lab.omglolwtfbbq.com/application/o/immich/.well-known/openid-configuration
  clientId: $OAUTH_CLIENT_ID
  clientSecret: $OAUTH_CLIENT_SECRET
  autoLaunch: false
  autoRegister: true
  scope: openid email profile
  storageLabelClaim: preferred_username
  timeout: 30000
  tokenEndpointAuthMethod: client_secret_post

passwordLogin:
  enabled: false

